spring:
  application:
    name: app-management-ms
  datasource:
    url: ${APP_MS_DB_URL:jdbc:mysql://localhost:3306/app_ms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${APP_MS_DB_USERNAME:root}
    password: ${APP_MS_DB_PASSWORD:}
    hikari:
      maximum-pool-size: ${APP_MS_DB_POOL_SIZE:10}
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
server:
  port: ${APP_MS_PORT:8080}
